sudo: false
language: ruby
cache:
  directories:
    - node_modules
    - /home/travis/.rvm/gems
rvm:
  - 2.4.2
before_install:
  - gem install bundler -v 1.16.0
install:
  - bundle
script:
  - rubocop && bundle exec rspec
